# Generated by Django 4.1.7 on 2023-02-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('endereco_completo', models.CharField(max_length=250, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('numero', models.CharField(max_length=30, null=True)),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('rua', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('ponto_referencia', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('nm_completo', models.CharField(max_length=200, null=True)),
                ('nm_primeiro', models.CharField(max_length=200, null=True)),
                ('nm_ultimo', models.CharField(max_length=200, null=True)),
                ('cpf', models.BigIntegerField(null=True)),
                ('cpf_form', models.CharField(max_length=20, null=True)),
                ('rg', models.CharField(max_length=15, null=True)),
                ('rg_form', models.CharField(max_length=15, null=True)),
                ('is_estrangeiro', models.BooleanField(default=False)),
                ('passaporte', models.CharField(max_length=200, null=True)),
                ('passaporte_form', models.CharField(max_length=200, null=True)),
                ('local_nascimento', models.CharField(max_length=200, null=True)),
                ('dat_nasc', models.DateField(null=True)),
                ('naturalidade', models.CharField(max_length=200, null=True)),
                ('nascionalidade', models.CharField(max_length=200, null=True)),
                ('imagem', models.FileField(default='fotos/sem-foto.png', null=True, upload_to='fotos/usuarios')),
                ('nm_mae', models.CharField(max_length=200, null=True)),
                ('nm_pai', models.CharField(max_length=200, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Outros')], max_length=1, null=True)),
                ('pagamento', models.CharField(max_length=30, null=True)),
                ('anamnese', models.CharField(max_length=30, null=True)),
                ('exame_medico', models.CharField(max_length=30, null=True)),
                ('tratamento', models.CharField(max_length=30, null=True)),
                ('avaliacao', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
