# Generated by Django 4.1.7 on 2023-03-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
    ]
