# Generated by Django 4.1.7 on 2023-03-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_delete_empresafuncionariorelacao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='Empresa',
        ),
        migrations.AlterModelTable(
            name='filialempresa',
            table='Filial',
        ),
    ]
