# Generated by Django 4.1.7 on 2023-03-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_empresa_table_alter_filialempresa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
