# Generated by Django 4.1.7 on 2023-02-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariologin',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='endereco_completo',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='ponto_referencia',
        ),
        migrations.RemoveField(
            model_name='funcionariologin',
            name='rua',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cep',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_completo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='latitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='longitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ponto_referencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rua',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
