# Generated by Django 4.1.7 on 2023-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_login', '0003_funcionariologin_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariologin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='%(app_label)s_%(class)s_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='funcionariologin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(app_label)s_%(class)s_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
