# Generated by Django 4.1.7 on 2023-02-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_alter_funcionariologin_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariologin',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
