# Generated by Django 4.1.7 on 2023-02-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0005_funcionariologin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariologin',
            name='nm_primeiro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='funcionariologin',
            name='nm_ultimo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
