# Generated by Django 4.1.7 on 2023-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0006_funcionariologin_nm_primeiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariologin',
            name='tipo_conta',
            field=models.CharField(default='usr', max_length=200, null=True),
        ),
    ]
