# Generated by Django 4.1.7 on 2023-02-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_delete_empresafuncionariorelacao'),
        ('user_login', '0007_funcionariologin_tipo_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariologin',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='funcionariologin',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.filialempresa'),
        ),
    ]
