# Generated by Django 4.1.7 on 2023-03-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0010_funcionario_local_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='Funcionario',
        ),
        migrations.AlterModelTable(
            name='funcionariologin',
            table='FuncionarioLogin',
        ),
    ]
